name: "example-cron-action"
on:
  schedule:
    - cron:  '*/5 * * * *'    # At every 5th minute

jobs:
  singleJobName:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        

      - name: Do some work
        run: echo test

     
